# Generated by Django 4.2 on 2023-04-23 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_zip_code_order_zipcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
    ]
